drop database QuanLyBanTraSua;
create database if not exists QuanLyBanTraSua;

use QuanLyBanTraSua;


create table if not exists Users(
	userID int primary key unique,
    userName nvarchar(100) not null unique,
    userPassWord nvarchar(50) not null,
    userEmail nvarchar(100) not null unique,
    userPhoneNumber nvarchar(20) not null unique,
    userBirthday datetime not null ,
    userGender nvarchar(10) not null check(userGender in ('MALE', 'FEMALE', 'Unknown'))
);

create table if not exists Items(
	itemID int primary key unique,
    itemName nvarchar(100) not null,
    -- itemNameEnglish nvarchar(100) not null,
    itemPrice float check(itemPrice > 0) not null,
    itemQuantity int check (itemQuantity >= 0) not null,
    itemDescription text not null,
    itemPreview text not null,
    itemResources text not null
);

create table if not exists Orders(
	orderID int primary key unique,
    userID int not null,
    orderDate datetime not null,
    orderPaidDate datetime not null,
    constraint fk_Orders_Users foreign key(userID) references Users(userID)
);

create table if not exists OrderDetails(
	orderID int,
    itemID int,
    count int not null check(count >= 0),
    constraint primary key(orderID, itemID),
    constraint fk_OrderDetails_Orders foreign key(orderID) references Orders(orderID),
    constraint fk_OrderDetails_Items foreign key(itemID) references Items(itemID)
);

insert into Users(userID, userName, userPassWord, userEmail, userPhoneNumber, userBirthday, userGender)
values('10101', 'Adimin', 'e00cf25ad42683b3df678c61f42c6bda', 'trantu10032000@gmail.com','0334064778','2000-10-03','Male'),
	  ('1011', 'Adimin2', 'c84258e9c39059a89ab77d846ddab909', 'trantu1003@gmail.com','099923232','2000-02-15','Unknown'),
	  ('10102', 'Adimin3', '32cacb2f994f6b42183a1300d9a3e8d6', 'trantu2000@gmail.com','0583653653','2000-01-01','FEMALE');


insert into Items(itemID, itemName, itemPrice, itemQuantity, itemDescription, itemPreview, itemResources)
values('001', 'SỮA TƯƠI CHÂN TRÂU ĐƯỜNG HỔ ', '20000', '100','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('002', 'DÂU TẰM KEM PHÔ MAI', '20000', '100','Được làm từ trái dâu tằm tự nhiên, không sử dụng phẩm màu và hương liệu tổng hợp nên Dâu tằm kem phô mai hội tụ trọn vẹn hương vị thuần khiết nông sản Việt, giữ được màu sắc, hương vị nguyên bản của trái dâu tằm. Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy của kem phô mai chắc chắn sẽ mang đến một hành trình trải nghiệm hoàn toàn mới lạ cho vị giác của bạn.','Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy, mặn mặn của kem phô mai mang lại trải nghiệm thú vị khi uống.','trà, bột sữa,dâu tằm,phô mai'),
	  ('003', 'Trà sữa khoai môn', '20000', '100','Trà sữa khoai môn tuy không phải là thức uống mới nhưng nó vẫn giữ được độ hot với giới trẻ, đặc biệt là vào các khoảng thời gian hè nắng nóng. ','Trà sữa khoai môn có vị béo béo của sữa, mùi thơm của khoai môn cùng với chút vị chát nhẹ của trà. Thức uống này không quá ngọt và ngậy như những loại trà sữa có kem cheese, vị ngọt thanh mà vẫn có chút béo bùi là điểm cộng lớn nhất của trà sữa khoai môn. Trà sữa khoai môn một số nơi sẽ dùng bột khoai môn để pha chế hoặc có thể dùng củ khoai môn tươi xay lấy nước sẽ nguyên chất hơn. ','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('004', 'Trà sữa matcha đậu đỏ', '20000', '100','Nếu trà sữa matcha là thức uống quá quen thuộc và phổ biến thì trà sữa matcha đậu đỏ lại là sản phẩm mới, thích hợp giải nhiệt dành cho mùa hè nắng nóng. Trà sữa Matcha đậu đỏ về cơ bản vẫn là trà sữa trà xanh với vị chát nhẹ của trà, vị thơm mát của matcha cùng với chút ngọt nhẹ của sữa tươi.','Đặc điểm nổi bật so với các loại trà sữa khác: phần đậu đỏ được xem như topping được rải phía trên bề mặt cốc trà. Phần đậu đỏ này có mùi thơm và vị ngon ngọt đặc trưng, khi uống kết hợp cùng matcha the mát sẽ tạo nên sự hòa quyện hương vị hoàn hảo ở đầu lưỡi.','trà, bột sữa,đậu đỏ,phô mai'),
      ('005', 'Trà sữa Oreo Chocolate Cream', '20000', '100','Trong số các loại trà sữa phổ biến thì trà sữa Oreo Chocolate Cream là một loại trà sữa khá mới trong thời gian gần đây. Với những người hảo ngọt thì vị béo ngậy của cốc trà này sẽ làm bạn phải mê mẩn. Phần trà sữa thơm ngọt kết hợp cùng lớp bọt kem mặn, đặc biệt là mùi thơm quyến rũ của chocolate cùng bánh Oreo.',' Vị béo ngậy của lớp kem cùng vị ngọt của sữa trong trà sẽ không làm bạn cảm thấy quá ngán nhờ chút đắng mà chocolate cùng vụn bánh Oreo mang lại.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('006', 'Trà sữa Pudding đậu đỏ', '20000', '100','Đây là loại trà sữa có topping gồm phần pudding trứng cùng với hạt đậu đỏ. Về phần trà sữa thì ngoài vị chát nhẹ cùng vị ngọt béo của sữa và trà thì điểm nhấn của cốc trà sữa này nằm ở phần pudding trứng cùng đậu đỏ phía trên.','Pudding trứng mềm mại, có vị ngọt và thơm, pha chút béo ngậy của vani và có màu vàng óng ngọt ngào, đi kèm đó là những hạt đậu đỏ mềm nhuyễn cũng có vị ngọt nhưng lại khá bùi khi nhai. 2 nguyên liệu này kết hợp cùng trà sữa tạo thành trà sữa Pudding đậu đỏ thích hợp giải nhiệt mùa hè','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('007', 'Trà sữa trân châu đen và trà sữa trân châu trắng', '20000', '100','Trà sữa trân châu đen và trà sữa trân châu trắng hẳn là 2 thức uống có mặt lâu nhất trong các menu tại các quán trà sữa cũng như các quán ăn vặt. Không phải tự nhiên mà 2 loại thức uống này vẫn tồn tại và được lòng nhiều người bên cạnh hàng loạt các sản phẩm trà sữa mới.','Trà sữa trân châu đen luôn là sự kết hợp hoàn hảo giữa trà đen, sữa tươi cùng hạt trân châu mềm, dai và có chút vị ngọt nhẹ. Uống và cảm nhận vị chát của trà, vị ngọt lẫn chút thơm của sữa cùng với những hạt trân châu đen dai dai hẳn là một lựa chọn khá hoàn hảo cho không chỉ riêng mùa hè.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('008', ' Trà sữa sương sáo', '20000', '100','Sương sáo, sương sa là những nguyên liệu phổ biến tại các tỉnh miền Nam và cực thích hợp cho những ngày hè nắng nóng. Sương sáo có tính giải nhiệt cao cùng với đó là nhiều công dụng tốt cho sức khỏe. Trà sữa sương sáo là sự kết hợp giữa trà sữa truyền thống với phần sương sáo mát lạnh.','Đặc điểm đặc trưng so với các loại trà sữa khác: có vị không quá ngọt béo hay ngọt ngậy như các loại trà sữa khác. Thay vào đó là vị ngọt thanh của sương sáo mà vẫn có chút thơm béo béo của sữa tươi và vị chát nhẹ của trà. Trà sữa sương sáo có độ ngọt vừa phải, có mùi thơm đặc trưng cũng như có tính giải khát cao.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('009', 'Trà sữa Earl Grey', '20000', '100','Trà sữa Earl Grey hay còn gọi là Trà Bá Tước là một loại trà sữa độc đáo được làm từ trà xuất xứ từ nước Anh với công đoạn ướp khá cầu kỳ. Trà sữa Earl Grey có vị khá chát và đắng nhẹ, đặc biệt là mùi thơm rất đặc trưng mà không phải loại trà nào cũng có.','Đặc điểm đặc trưng khác với các loại trà sữa khác: Điểm nhấn của trà sữa Earl Grey là tinh dầu cam đắng Bergamot, kết hợp cùng vị béo ngậy của lớp kem mặn phía trên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0010', 'Trà sữa Caramel', '20000', '100','Caramel hẳn là một món ăn, một nguyên liệu phổ biến đặc biệt với giới trẻ. Chỉ riêng caramel cũng có thể kết hợp được với vô số nguyên liệu khác để tạo thành những món ăn ngon và hấp dẫn. Trà sữa caramel được làm từ trà sữa truyền thống kết hợp cùng lớp kem caramel thơm và béo ngậy.','Đặc điểm đặc trưng so với các loại trà sữa khác: phần trà sữa ngọt dịu kết hợp cùng lớp kem caramel thơm thơm, béo béo, tạo nên tổng thể một thức uống không quá ngọt những vẫn có mùi béo ngậy hấp dẫn nhiều người.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0011', 'Trà sữa Cà phê', '20000', '100','Nhắc tới cà phê là nhắc tới một loại đồ uống truyền thống của người dân Việt Nam. Hương vị của cà phê có chút đắng, khác với vị đắng của chocolate. Đặc biệt thì cà phê cũng có mùi thơm quyến rũ mà chỉ cần ngửi cũng muốn được uống thử. Trà sữa cà phê hẳn là sự kết hợp khá độc đáo giữa 2 nguyên liệu tưởng chừng có ít sự liên quan này với nhau.','Đặc điểm đặc trưng so với các loại trà sữa khác:  cho dù có mùi vị cà phê nhưng vị chát nhẹ của trà đen vẫn được giữ nguyên, vị thơm của trà và cà phê không những không át nhau mà còn hòa quyện tạo nên mùi hương độc đáo. Ngoài ra chút vị đắng nhẹ của cà phê cũng rất thích hợp để kết hợp cùng vị ngọt bùi của sữa.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường' ),
	  ('0012', 'Lục trà sữa', '20000', '100','Lục trà sữa là một loại trà sữa phổ biến và có mặt hầu như các menu của các tiệm trà sữa. Lục trà sữa ngoài vị chát nhẹ thì còn có vị thơm nồng và ngọt ngọt của sữa. Lục trà sữa có nhiều sữa hơn so với hồng trà sữa.','Đặc điểm đặc trưng so với các loại trà sữa khác: thức uống này có thể kết hợp thêm các vị như kiwi, dâu, táo, nho,…để tăng thêm độ thơm ngon. Lục trà sữa chủ yếu hợp với topping như trân châu đen, trân châu trắng','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0013', 'Trà sữa cheese milk foam', '20000', '100','Trà sữa cheese milk foam là một loại đồ uống được giới trẻ đặc biệt yêu thích thời gian đổ lại đây. Ngoài vị trà sữa truyền thống thì cốc trà còn được thêm một lớp kem sữa béo béo, ngậy ngậy tràn mùi thơm.','Điểm đặc trưng so với các loại trà sữa khác: lớp kem sữa này nay còn có cả cheese, tạo nên một món đồ uống trà kem sữa vị phô mai mặn mặn, béo ngậy pha chút chát nhẹ và ngọt dịu của sữa và trà.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0014', 'Cha yen – Thái Lan', '20000', '100','Không quá xa lạ với giới trẻ Việt Nam, Cha yen (tên gọi trong tiếng Thái của trà sữa Thái) là một điểm sáng về văn hóa ẩm thực đường phố Thái Lan, nhờ vào quá trình chế biến trà cực độc đáo. ','Cha yen có hai loại: trà đỏ và trà xanh. Trà đỏ là loại trà sữa truyền thống, trà xanh có mùi thơm nhẹ và thanh hơn. Cha yen có vị ngọt khá gắt, beo béo, có tác dụng giải nhiệt khá tốt khi dùng lạnh, rất phù hợp với khí hậu nóng quanh năm của xứ sở chùa vàng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0015', 'Trà sữa túi lọc', '20000', '100','Là xứ sở của trà, Việt Nam không thiếu những phiên bản trà sữa hảo hạng với giá thành từ trung bình đến cao cấp, nhưng trà sữa túi lọc hoàn toàn phản ánh đúng bản chất của người Việt Nam, cụ thể là người Sài Gòn: gọn nhẹ, gần gũi và dân dã.','Dân dã, tiện lợi và sáng tạo, trà sữa túi lọc là một phiên bản trà sữa đặc sắc của Việt Nam.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0016', 'Po cha – trà bơ Tây Tạng', '20000', '100','Nguyên liệu để pha trà bơ có lẽ là những cái tên còn khá xa lạ với người Việt: trà đen Pu-erh, bơ làm từ sữa bò Yak (đây là loại bò đặc trưng của vùng đất này) và muối Himalaya (một loại muối mỏ màu hồng có tác dụng chữa bệnh). Thời gian đun trà Pu-erh khoảng 1 tiếng, lâu hơn so với trà thông thường, sau đó người ta sẽ cho sữa và muối vào. Sau đó, họ dùng bình trà có tên là Chandong để hòa tan trà sữa vừa đun với bơ. Mùi vị thơm nhẹ, dễ uống, vừa giữ ấm tốt, vừa chống đói hiệu quả, nếu có dịp ghé thăm Tây Tạng, đừng quên trà bơ Po cha nhé.','Trà bơ Po cha không chỉ là thức uống truyền thống của người Tây Tạng, mà còn là “thần dược” giúp họ sinh tồn trong cái lạnh cắt da cắt thịt của vùng đất khắc nghiệt này.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0017', 'Masala chai – Pakistan, Ấn Độ', '20000', '100','Trà Masala chai là một thức uống giải khát có mùi vị trà, được làm bằng cách ủ trà đen với hỗn hợp các loại gia vị và thảo mộc Ấn Độ. Cho đến nay, Masala chai đã vươn ra toàn thế giới, ở một số nước, nó còn trở thành một nét đặc trưng chủ đạo của các quán cà phê cũng như phòng trà.','Để chế biến Masala chai, cách đơn giản nhất theo kiểu truyền thống là nấu cô bằng cách ninh lửa nhỏ hoặc nấu sôi hỗn hợp sữa và nước với trà được làm tơi, chất làm ngọt cùng tất cả các gia vị khác. Với hỗn hợp nguyên liệu lạ và đậm chất Nam Á, chắc chắn hương vị của Masala chai sẽ nồng đậm nhưng vẫn ngọt ngào, khiến du khách lưu luyến mãi.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0018', 'Trà sữa “hoàng gia” Nhật Bản', '20000', '100','Thật ra, tên gọi “trà sữa hoàng gia” là tên một thương hiệu trà sữa pha sẵn nổi tiếng của Nhật Bản, chứ không phải loại trà sữa được phục vụ trong cung đình. Tuy nhiên, món trà sữa này được nhiều người Nhật Bản yêu thích vì vị thơm ngon của nó.','Thay vì sử dụng nước pha với bột trà và thêm sữa đặc, người Nhật đun sữa đến khi vừa sôi thì cho bột trà vào. Khi ấy, mùi thơm khó cưỡng của trà sẽ bốc lên ngay lập tức, quyện với hương thơm của sữa đun sôi. Và đến khi dòng trà sữa hoàng gia ngọt ngào chạm đầu lưỡi, bạn sẽ hiểu vì sao nó được ưa chuộng ở Nhật Bản đến như vậy.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0019', 'Trà sữa trân châu Đài Loan', '20000', '100','Những li trà sữa với hạt trân châu đen hấp dẫn gây sốt trong giới trẻ Việt có nguồn gốc từ Đài Loan. Có thể nói, trà sữa Đài Loan đa dạng và phong phú bậc nhất trong số những phiên bản trà sữa trên khắp thế giới','Có đến gần 100 loại trà sữa cho bạn tha hồ lựa chọn nếu bước vào một quán trà sữa Đài Loan cùng nhiều loại hạt, trân châu vừa thích mắt vừa vui miệng. Đây là lí do khiến trà sữa Đài Loan được chào đón và yêu thích khi “đặt chân” đến các nước châu Á khác.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0020', 'TOCO SOCOLA ', '20000', '100','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng socola, một chút đắng, chút ngọt cực kì hấp dẫn.','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng, một chút đắng, chút ngọt cực kì hấp dẫn là sự kết hợp hoàn hảo của hương vị socola với hương thơm ngọt mát từ trà.Sẽ lại càng ngon hơn nếu Toco Socola được kết hợp với bánh pudding và trân trâu đen, tất cả sẽ làm nên một đồ uống tuyệt hảo khó quên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0021', 'TRÀ DÂU TẰM PHA LÊ TUYẾT', '20000', '100','Mứt dâu tằm hòa quyện cùng với trà xanh cùng những viên thạch băng tuyết dai dai cho ly trà dâu tằm thanh mát. Đặc biệt dâu tằm giúp trí não minh mẫn, thạch băng tuyết có lợi cho tiêu hóa.','Mứt dâu khi được hòa quyện cùng nước trà xanh tưởng chừng đối nghịch giữa ngọt – chát nhưng hóa ra lại bổ trợ tương hỗ cho nhau không ngờ, tạo nên một thức uống vừa quen vừa lạ.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0022', 'TRÀ SỮA PANDA ', '20000', '100','Hương trà nhài thơm mát cùng vị ngọt ngậy béo sữa kết hợp cùng sợi trân châu hoàng kim và trân châu sợi dai mềm.','Khi thưởng thức trà sữa Panda, khách hàng có thể cảm nhận rõ hương trà nhài thơm mát cùng vị ngọt ngậy béo của trà và sữa kết hợp cùng sợi trân châu dẻo dai. Trà của TocoToco, sau khi được thu hoạch từ những nông trường lớn, sẽ được ủ với hương hoa hài nên luôn tạo một hương vị nhẹ nhàng, thoang thoảng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0023', 'TRÀ SỮA BA ANH EM ', '20000', '100','Bộ ba topping thần thánh - "Trân châu hoàng kim dẻo mềm, thạch sương sáo thanh mát và bánh pudding mềm mịn" kết hợp hoàn hảo cùng vị ngậy béo của sữa và thanh mát của trà cho ra đời ly trà sữa ngon đúng điệu.','Là sự hòa quyện giữ vị nồng đặc trưng từ hồng trà sữa kết hợp với mùi sữa thơm ngậy. Đúng như tên gọi, trà sữa Ba anh em gồm 3 topping: trân châu dai dòn từ 100% tinh bột sắn, pudding, rau câu mềm, thanh, mát lạnh, vị ngọt tan dần đầu lưỡi, đánh thức từng tế bào vị giác.Thử Trà sữa Ba Anh Em ngay và liền nha, bạn sẽ không hối hận về lựa chọn của mình đâu!','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0024', 'SỮA TƯƠI CHÂN TRÂU ĐƯỜNG HỔ ', '20000', '100','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0025', 'DÂU TẰM KEM PHÔ MAI', '20000', '100','Được làm từ trái dâu tằm tự nhiên, không sử dụng phẩm màu và hương liệu tổng hợp nên Dâu tằm kem phô mai hội tụ trọn vẹn hương vị thuần khiết nông sản Việt, giữ được màu sắc, hương vị nguyên bản của trái dâu tằm. Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy của kem phô mai chắc chắn sẽ mang đến một hành trình trải nghiệm hoàn toàn mới lạ cho vị giác của bạn.','Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy, mặn mặn của kem phô mai mang lại trải nghiệm thú vị khi uống.','trà, bột sữa,dâu tằm,phô mai'),
	  ('0026', 'Trà sữa khoai môn', '20000', '100','Trà sữa khoai môn tuy không phải là thức uống mới nhưng nó vẫn giữ được độ hot với giới trẻ, đặc biệt là vào các khoảng thời gian hè nắng nóng. ','Trà sữa khoai môn có vị béo béo của sữa, mùi thơm của khoai môn cùng với chút vị chát nhẹ của trà. Thức uống này không quá ngọt và ngậy như những loại trà sữa có kem cheese, vị ngọt thanh mà vẫn có chút béo bùi là điểm cộng lớn nhất của trà sữa khoai môn. Trà sữa khoai môn một số nơi sẽ dùng bột khoai môn để pha chế hoặc có thể dùng củ khoai môn tươi xay lấy nước sẽ nguyên chất hơn. ','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0027', 'Trà sữa matcha đậu đỏ', '20000', '100','Nếu trà sữa matcha là thức uống quá quen thuộc và phổ biến thì trà sữa matcha đậu đỏ lại là sản phẩm mới, thích hợp giải nhiệt dành cho mùa hè nắng nóng. Trà sữa Matcha đậu đỏ về cơ bản vẫn là trà sữa trà xanh với vị chát nhẹ của trà, vị thơm mát của matcha cùng với chút ngọt nhẹ của sữa tươi.','Đặc điểm nổi bật so với các loại trà sữa khác: phần đậu đỏ được xem như topping được rải phía trên bề mặt cốc trà. Phần đậu đỏ này có mùi thơm và vị ngon ngọt đặc trưng, khi uống kết hợp cùng matcha the mát sẽ tạo nên sự hòa quyện hương vị hoàn hảo ở đầu lưỡi.','trà, bột sữa,đậu đỏ,phô mai'),
      ('0028', 'Trà sữa Oreo Chocolate Cream', '20000', '100','Trong số các loại trà sữa phổ biến thì trà sữa Oreo Chocolate Cream là một loại trà sữa khá mới trong thời gian gần đây. Với những người hảo ngọt thì vị béo ngậy của cốc trà này sẽ làm bạn phải mê mẩn. Phần trà sữa thơm ngọt kết hợp cùng lớp bọt kem mặn, đặc biệt là mùi thơm quyến rũ của chocolate cùng bánh Oreo.',' Vị béo ngậy của lớp kem cùng vị ngọt của sữa trong trà sẽ không làm bạn cảm thấy quá ngán nhờ chút đắng mà chocolate cùng vụn bánh Oreo mang lại.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0029', 'Trà sữa Pudding đậu đỏ', '20000', '100','Đây là loại trà sữa có topping gồm phần pudding trứng cùng với hạt đậu đỏ. Về phần trà sữa thì ngoài vị chát nhẹ cùng vị ngọt béo của sữa và trà thì điểm nhấn của cốc trà sữa này nằm ở phần pudding trứng cùng đậu đỏ phía trên.','Pudding trứng mềm mại, có vị ngọt và thơm, pha chút béo ngậy của vani và có màu vàng óng ngọt ngào, đi kèm đó là những hạt đậu đỏ mềm nhuyễn cũng có vị ngọt nhưng lại khá bùi khi nhai. 2 nguyên liệu này kết hợp cùng trà sữa tạo thành trà sữa Pudding đậu đỏ thích hợp giải nhiệt mùa hè','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0030', 'Trà sữa trân châu đen và trà sữa trân châu trắng', '20000', '100','Trà sữa trân châu đen và trà sữa trân châu trắng hẳn là 2 thức uống có mặt lâu nhất trong các menu tại các quán trà sữa cũng như các quán ăn vặt. Không phải tự nhiên mà 2 loại thức uống này vẫn tồn tại và được lòng nhiều người bên cạnh hàng loạt các sản phẩm trà sữa mới.','Trà sữa trân châu đen luôn là sự kết hợp hoàn hảo giữa trà đen, sữa tươi cùng hạt trân châu mềm, dai và có chút vị ngọt nhẹ. Uống và cảm nhận vị chát của trà, vị ngọt lẫn chút thơm của sữa cùng với những hạt trân châu đen dai dai hẳn là một lựa chọn khá hoàn hảo cho không chỉ riêng mùa hè.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0031', ' Trà sữa sương sáo', '20000', '100','Sương sáo, sương sa là những nguyên liệu phổ biến tại các tỉnh miền Nam và cực thích hợp cho những ngày hè nắng nóng. Sương sáo có tính giải nhiệt cao cùng với đó là nhiều công dụng tốt cho sức khỏe. Trà sữa sương sáo là sự kết hợp giữa trà sữa truyền thống với phần sương sáo mát lạnh.','Đặc điểm đặc trưng so với các loại trà sữa khác: có vị không quá ngọt béo hay ngọt ngậy như các loại trà sữa khác. Thay vào đó là vị ngọt thanh của sương sáo mà vẫn có chút thơm béo béo của sữa tươi và vị chát nhẹ của trà. Trà sữa sương sáo có độ ngọt vừa phải, có mùi thơm đặc trưng cũng như có tính giải khát cao.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0032', 'Trà sữa Earl Grey', '20000', '100','Trà sữa Earl Grey hay còn gọi là Trà Bá Tước là một loại trà sữa độc đáo được làm từ trà xuất xứ từ nước Anh với công đoạn ướp khá cầu kỳ. Trà sữa Earl Grey có vị khá chát và đắng nhẹ, đặc biệt là mùi thơm rất đặc trưng mà không phải loại trà nào cũng có.','Đặc điểm đặc trưng khác với các loại trà sữa khác: Điểm nhấn của trà sữa Earl Grey là tinh dầu cam đắng Bergamot, kết hợp cùng vị béo ngậy của lớp kem mặn phía trên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0033', 'Trà sữa Caramel', '20000', '100','Caramel hẳn là một món ăn, một nguyên liệu phổ biến đặc biệt với giới trẻ. Chỉ riêng caramel cũng có thể kết hợp được với vô số nguyên liệu khác để tạo thành những món ăn ngon và hấp dẫn. Trà sữa caramel được làm từ trà sữa truyền thống kết hợp cùng lớp kem caramel thơm và béo ngậy.','Đặc điểm đặc trưng so với các loại trà sữa khác: phần trà sữa ngọt dịu kết hợp cùng lớp kem caramel thơm thơm, béo béo, tạo nên tổng thể một thức uống không quá ngọt những vẫn có mùi béo ngậy hấp dẫn nhiều người.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0034', 'Trà sữa Cà phê', '20000', '100','Nhắc tới cà phê là nhắc tới một loại đồ uống truyền thống của người dân Việt Nam. Hương vị của cà phê có chút đắng, khác với vị đắng của chocolate. Đặc biệt thì cà phê cũng có mùi thơm quyến rũ mà chỉ cần ngửi cũng muốn được uống thử. Trà sữa cà phê hẳn là sự kết hợp khá độc đáo giữa 2 nguyên liệu tưởng chừng có ít sự liên quan này với nhau.','Đặc điểm đặc trưng so với các loại trà sữa khác:  cho dù có mùi vị cà phê nhưng vị chát nhẹ của trà đen vẫn được giữ nguyên, vị thơm của trà và cà phê không những không át nhau mà còn hòa quyện tạo nên mùi hương độc đáo. Ngoài ra chút vị đắng nhẹ của cà phê cũng rất thích hợp để kết hợp cùng vị ngọt bùi của sữa.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường' ),
	  ('0035', 'Lục trà sữa', '20000', '100','Lục trà sữa là một loại trà sữa phổ biến và có mặt hầu như các menu của các tiệm trà sữa. Lục trà sữa ngoài vị chát nhẹ thì còn có vị thơm nồng và ngọt ngọt của sữa. Lục trà sữa có nhiều sữa hơn so với hồng trà sữa.','Đặc điểm đặc trưng so với các loại trà sữa khác: thức uống này có thể kết hợp thêm các vị như kiwi, dâu, táo, nho,…để tăng thêm độ thơm ngon. Lục trà sữa chủ yếu hợp với topping như trân châu đen, trân châu trắng','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0036', 'Trà sữa cheese milk foam', '20000', '100','Trà sữa cheese milk foam là một loại đồ uống được giới trẻ đặc biệt yêu thích thời gian đổ lại đây. Ngoài vị trà sữa truyền thống thì cốc trà còn được thêm một lớp kem sữa béo béo, ngậy ngậy tràn mùi thơm.','Điểm đặc trưng so với các loại trà sữa khác: lớp kem sữa này nay còn có cả cheese, tạo nên một món đồ uống trà kem sữa vị phô mai mặn mặn, béo ngậy pha chút chát nhẹ và ngọt dịu của sữa và trà.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0037', 'Cha yen – Thái Lan', '20000', '100','Không quá xa lạ với giới trẻ Việt Nam, Cha yen (tên gọi trong tiếng Thái của trà sữa Thái) là một điểm sáng về văn hóa ẩm thực đường phố Thái Lan, nhờ vào quá trình chế biến trà cực độc đáo. ','Cha yen có hai loại: trà đỏ và trà xanh. Trà đỏ là loại trà sữa truyền thống, trà xanh có mùi thơm nhẹ và thanh hơn. Cha yen có vị ngọt khá gắt, beo béo, có tác dụng giải nhiệt khá tốt khi dùng lạnh, rất phù hợp với khí hậu nóng quanh năm của xứ sở chùa vàng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0038', 'Trà sữa túi lọc', '20000', '100','Là xứ sở của trà, Việt Nam không thiếu những phiên bản trà sữa hảo hạng với giá thành từ trung bình đến cao cấp, nhưng trà sữa túi lọc hoàn toàn phản ánh đúng bản chất của người Việt Nam, cụ thể là người Sài Gòn: gọn nhẹ, gần gũi và dân dã.','Dân dã, tiện lợi và sáng tạo, trà sữa túi lọc là một phiên bản trà sữa đặc sắc của Việt Nam.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0039', 'Po cha – trà bơ Tây Tạng', '20000', '100','Nguyên liệu để pha trà bơ có lẽ là những cái tên còn khá xa lạ với người Việt: trà đen Pu-erh, bơ làm từ sữa bò Yak (đây là loại bò đặc trưng của vùng đất này) và muối Himalaya (một loại muối mỏ màu hồng có tác dụng chữa bệnh). Thời gian đun trà Pu-erh khoảng 1 tiếng, lâu hơn so với trà thông thường, sau đó người ta sẽ cho sữa và muối vào. Sau đó, họ dùng bình trà có tên là Chandong để hòa tan trà sữa vừa đun với bơ. Mùi vị thơm nhẹ, dễ uống, vừa giữ ấm tốt, vừa chống đói hiệu quả, nếu có dịp ghé thăm Tây Tạng, đừng quên trà bơ Po cha nhé.','Trà bơ Po cha không chỉ là thức uống truyền thống của người Tây Tạng, mà còn là “thần dược” giúp họ sinh tồn trong cái lạnh cắt da cắt thịt của vùng đất khắc nghiệt này.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0040', 'Masala chai – Pakistan, Ấn Độ', '20000', '100','Trà Masala chai là một thức uống giải khát có mùi vị trà, được làm bằng cách ủ trà đen với hỗn hợp các loại gia vị và thảo mộc Ấn Độ. Cho đến nay, Masala chai đã vươn ra toàn thế giới, ở một số nước, nó còn trở thành một nét đặc trưng chủ đạo của các quán cà phê cũng như phòng trà.','Để chế biến Masala chai, cách đơn giản nhất theo kiểu truyền thống là nấu cô bằng cách ninh lửa nhỏ hoặc nấu sôi hỗn hợp sữa và nước với trà được làm tơi, chất làm ngọt cùng tất cả các gia vị khác. Với hỗn hợp nguyên liệu lạ và đậm chất Nam Á, chắc chắn hương vị của Masala chai sẽ nồng đậm nhưng vẫn ngọt ngào, khiến du khách lưu luyến mãi.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0041', 'Trà sữa “hoàng gia” Nhật Bản', '20000', '100','Thật ra, tên gọi “trà sữa hoàng gia” là tên một thương hiệu trà sữa pha sẵn nổi tiếng của Nhật Bản, chứ không phải loại trà sữa được phục vụ trong cung đình. Tuy nhiên, món trà sữa này được nhiều người Nhật Bản yêu thích vì vị thơm ngon của nó.','Thay vì sử dụng nước pha với bột trà và thêm sữa đặc, người Nhật đun sữa đến khi vừa sôi thì cho bột trà vào. Khi ấy, mùi thơm khó cưỡng của trà sẽ bốc lên ngay lập tức, quyện với hương thơm của sữa đun sôi. Và đến khi dòng trà sữa hoàng gia ngọt ngào chạm đầu lưỡi, bạn sẽ hiểu vì sao nó được ưa chuộng ở Nhật Bản đến như vậy.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0042', 'Trà sữa trân châu Đài Loan', '20000', '100','Những li trà sữa với hạt trân châu đen hấp dẫn gây sốt trong giới trẻ Việt có nguồn gốc từ Đài Loan. Có thể nói, trà sữa Đài Loan đa dạng và phong phú bậc nhất trong số những phiên bản trà sữa trên khắp thế giới','Có đến gần 100 loại trà sữa cho bạn tha hồ lựa chọn nếu bước vào một quán trà sữa Đài Loan cùng nhiều loại hạt, trân châu vừa thích mắt vừa vui miệng. Đây là lí do khiến trà sữa Đài Loan được chào đón và yêu thích khi “đặt chân” đến các nước châu Á khác.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0043', 'TOCO SOCOLA ', '20000', '100','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng socola, một chút đắng, chút ngọt cực kì hấp dẫn.','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng, một chút đắng, chút ngọt cực kì hấp dẫn là sự kết hợp hoàn hảo của hương vị socola với hương thơm ngọt mát từ trà.Sẽ lại càng ngon hơn nếu Toco Socola được kết hợp với bánh pudding và trân trâu đen, tất cả sẽ làm nên một đồ uống tuyệt hảo khó quên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0044', 'TRÀ DÂU TẰM PHA LÊ TUYẾT', '20000', '100','Mứt dâu tằm hòa quyện cùng với trà xanh cùng những viên thạch băng tuyết dai dai cho ly trà dâu tằm thanh mát. Đặc biệt dâu tằm giúp trí não minh mẫn, thạch băng tuyết có lợi cho tiêu hóa.','Mứt dâu khi được hòa quyện cùng nước trà xanh tưởng chừng đối nghịch giữa ngọt – chát nhưng hóa ra lại bổ trợ tương hỗ cho nhau không ngờ, tạo nên một thức uống vừa quen vừa lạ.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0045', 'TRÀ SỮA PANDA ', '20000', '100','Hương trà nhài thơm mát cùng vị ngọt ngậy béo sữa kết hợp cùng sợi trân châu hoàng kim và trân châu sợi dai mềm.','Khi thưởng thức trà sữa Panda, khách hàng có thể cảm nhận rõ hương trà nhài thơm mát cùng vị ngọt ngậy béo của trà và sữa kết hợp cùng sợi trân châu dẻo dai. Trà của TocoToco, sau khi được thu hoạch từ những nông trường lớn, sẽ được ủ với hương hoa hài nên luôn tạo một hương vị nhẹ nhàng, thoang thoảng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0046', 'TRÀ SỮA BA ANH EM ', '20000', '100','Bộ ba topping thần thánh - "Trân châu hoàng kim dẻo mềm, thạch sương sáo thanh mát và bánh pudding mềm mịn" kết hợp hoàn hảo cùng vị ngậy béo của sữa và thanh mát của trà cho ra đời ly trà sữa ngon đúng điệu.','Là sự hòa quyện giữ vị nồng đặc trưng từ hồng trà sữa kết hợp với mùi sữa thơm ngậy. Đúng như tên gọi, trà sữa Ba anh em gồm 3 topping: trân châu dai dòn từ 100% tinh bột sắn, pudding, rau câu mềm, thanh, mát lạnh, vị ngọt tan dần đầu lưỡi, đánh thức từng tế bào vị giác.Thử Trà sữa Ba Anh Em ngay và liền nha, bạn sẽ không hối hận về lựa chọn của mình đâu!','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0047', 'SỮA TƯƠI CHÂN TRÂU ĐƯỜNG HỔ ', '20000', '100','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0048', 'DÂU TẰM KEM PHÔ MAI', '20000', '100','Được làm từ trái dâu tằm tự nhiên, không sử dụng phẩm màu và hương liệu tổng hợp nên Dâu tằm kem phô mai hội tụ trọn vẹn hương vị thuần khiết nông sản Việt, giữ được màu sắc, hương vị nguyên bản của trái dâu tằm. Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy của kem phô mai chắc chắn sẽ mang đến một hành trình trải nghiệm hoàn toàn mới lạ cho vị giác của bạn.','Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy, mặn mặn của kem phô mai mang lại trải nghiệm thú vị khi uống.','trà, bột sữa,dâu tằm,phô mai'),
	  ('0049', 'Trà sữa khoai môn', '20000', '100','Trà sữa khoai môn tuy không phải là thức uống mới nhưng nó vẫn giữ được độ hot với giới trẻ, đặc biệt là vào các khoảng thời gian hè nắng nóng. ','Trà sữa khoai môn có vị béo béo của sữa, mùi thơm của khoai môn cùng với chút vị chát nhẹ của trà. Thức uống này không quá ngọt và ngậy như những loại trà sữa có kem cheese, vị ngọt thanh mà vẫn có chút béo bùi là điểm cộng lớn nhất của trà sữa khoai môn. Trà sữa khoai môn một số nơi sẽ dùng bột khoai môn để pha chế hoặc có thể dùng củ khoai môn tươi xay lấy nước sẽ nguyên chất hơn. ','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0050', 'Trà sữa matcha đậu đỏ', '20000', '100','Nếu trà sữa matcha là thức uống quá quen thuộc và phổ biến thì trà sữa matcha đậu đỏ lại là sản phẩm mới, thích hợp giải nhiệt dành cho mùa hè nắng nóng. Trà sữa Matcha đậu đỏ về cơ bản vẫn là trà sữa trà xanh với vị chát nhẹ của trà, vị thơm mát của matcha cùng với chút ngọt nhẹ của sữa tươi.','Đặc điểm nổi bật so với các loại trà sữa khác: phần đậu đỏ được xem như topping được rải phía trên bề mặt cốc trà. Phần đậu đỏ này có mùi thơm và vị ngon ngọt đặc trưng, khi uống kết hợp cùng matcha the mát sẽ tạo nên sự hòa quyện hương vị hoàn hảo ở đầu lưỡi.','trà, bột sữa,đậu đỏ,phô mai'),
      ('0051', 'Trà sữa Oreo Chocolate Cream', '20000', '100','Trong số các loại trà sữa phổ biến thì trà sữa Oreo Chocolate Cream là một loại trà sữa khá mới trong thời gian gần đây. Với những người hảo ngọt thì vị béo ngậy của cốc trà này sẽ làm bạn phải mê mẩn. Phần trà sữa thơm ngọt kết hợp cùng lớp bọt kem mặn, đặc biệt là mùi thơm quyến rũ của chocolate cùng bánh Oreo.',' Vị béo ngậy của lớp kem cùng vị ngọt của sữa trong trà sẽ không làm bạn cảm thấy quá ngán nhờ chút đắng mà chocolate cùng vụn bánh Oreo mang lại.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0052', 'Trà sữa Pudding đậu đỏ', '20000', '100','Đây là loại trà sữa có topping gồm phần pudding trứng cùng với hạt đậu đỏ. Về phần trà sữa thì ngoài vị chát nhẹ cùng vị ngọt béo của sữa và trà thì điểm nhấn của cốc trà sữa này nằm ở phần pudding trứng cùng đậu đỏ phía trên.','Pudding trứng mềm mại, có vị ngọt và thơm, pha chút béo ngậy của vani và có màu vàng óng ngọt ngào, đi kèm đó là những hạt đậu đỏ mềm nhuyễn cũng có vị ngọt nhưng lại khá bùi khi nhai. 2 nguyên liệu này kết hợp cùng trà sữa tạo thành trà sữa Pudding đậu đỏ thích hợp giải nhiệt mùa hè','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0053', 'Trà sữa trân châu đen và trà sữa trân châu trắng', '20000', '100','Trà sữa trân châu đen và trà sữa trân châu trắng hẳn là 2 thức uống có mặt lâu nhất trong các menu tại các quán trà sữa cũng như các quán ăn vặt. Không phải tự nhiên mà 2 loại thức uống này vẫn tồn tại và được lòng nhiều người bên cạnh hàng loạt các sản phẩm trà sữa mới.','Trà sữa trân châu đen luôn là sự kết hợp hoàn hảo giữa trà đen, sữa tươi cùng hạt trân châu mềm, dai và có chút vị ngọt nhẹ. Uống và cảm nhận vị chát của trà, vị ngọt lẫn chút thơm của sữa cùng với những hạt trân châu đen dai dai hẳn là một lựa chọn khá hoàn hảo cho không chỉ riêng mùa hè.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0054', ' Trà sữa sương sáo', '20000', '100','Sương sáo, sương sa là những nguyên liệu phổ biến tại các tỉnh miền Nam và cực thích hợp cho những ngày hè nắng nóng. Sương sáo có tính giải nhiệt cao cùng với đó là nhiều công dụng tốt cho sức khỏe. Trà sữa sương sáo là sự kết hợp giữa trà sữa truyền thống với phần sương sáo mát lạnh.','Đặc điểm đặc trưng so với các loại trà sữa khác: có vị không quá ngọt béo hay ngọt ngậy như các loại trà sữa khác. Thay vào đó là vị ngọt thanh của sương sáo mà vẫn có chút thơm béo béo của sữa tươi và vị chát nhẹ của trà. Trà sữa sương sáo có độ ngọt vừa phải, có mùi thơm đặc trưng cũng như có tính giải khát cao.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0055', 'Trà sữa Earl Grey', '20000', '100','Trà sữa Earl Grey hay còn gọi là Trà Bá Tước là một loại trà sữa độc đáo được làm từ trà xuất xứ từ nước Anh với công đoạn ướp khá cầu kỳ. Trà sữa Earl Grey có vị khá chát và đắng nhẹ, đặc biệt là mùi thơm rất đặc trưng mà không phải loại trà nào cũng có.','Đặc điểm đặc trưng khác với các loại trà sữa khác: Điểm nhấn của trà sữa Earl Grey là tinh dầu cam đắng Bergamot, kết hợp cùng vị béo ngậy của lớp kem mặn phía trên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0056', 'Trà sữa Caramel', '20000', '100','Caramel hẳn là một món ăn, một nguyên liệu phổ biến đặc biệt với giới trẻ. Chỉ riêng caramel cũng có thể kết hợp được với vô số nguyên liệu khác để tạo thành những món ăn ngon và hấp dẫn. Trà sữa caramel được làm từ trà sữa truyền thống kết hợp cùng lớp kem caramel thơm và béo ngậy.','Đặc điểm đặc trưng so với các loại trà sữa khác: phần trà sữa ngọt dịu kết hợp cùng lớp kem caramel thơm thơm, béo béo, tạo nên tổng thể một thức uống không quá ngọt những vẫn có mùi béo ngậy hấp dẫn nhiều người.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0057', 'Trà sữa Cà phê', '20000', '100','Nhắc tới cà phê là nhắc tới một loại đồ uống truyền thống của người dân Việt Nam. Hương vị của cà phê có chút đắng, khác với vị đắng của chocolate. Đặc biệt thì cà phê cũng có mùi thơm quyến rũ mà chỉ cần ngửi cũng muốn được uống thử. Trà sữa cà phê hẳn là sự kết hợp khá độc đáo giữa 2 nguyên liệu tưởng chừng có ít sự liên quan này với nhau.','Đặc điểm đặc trưng so với các loại trà sữa khác:  cho dù có mùi vị cà phê nhưng vị chát nhẹ của trà đen vẫn được giữ nguyên, vị thơm của trà và cà phê không những không át nhau mà còn hòa quyện tạo nên mùi hương độc đáo. Ngoài ra chút vị đắng nhẹ của cà phê cũng rất thích hợp để kết hợp cùng vị ngọt bùi của sữa.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường' ),
	  ('0058', 'Lục trà sữa', '20000', '100','Lục trà sữa là một loại trà sữa phổ biến và có mặt hầu như các menu của các tiệm trà sữa. Lục trà sữa ngoài vị chát nhẹ thì còn có vị thơm nồng và ngọt ngọt của sữa. Lục trà sữa có nhiều sữa hơn so với hồng trà sữa.','Đặc điểm đặc trưng so với các loại trà sữa khác: thức uống này có thể kết hợp thêm các vị như kiwi, dâu, táo, nho,…để tăng thêm độ thơm ngon. Lục trà sữa chủ yếu hợp với topping như trân châu đen, trân châu trắng','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0059', 'Trà sữa cheese milk foam', '20000', '100','Trà sữa cheese milk foam là một loại đồ uống được giới trẻ đặc biệt yêu thích thời gian đổ lại đây. Ngoài vị trà sữa truyền thống thì cốc trà còn được thêm một lớp kem sữa béo béo, ngậy ngậy tràn mùi thơm.','Điểm đặc trưng so với các loại trà sữa khác: lớp kem sữa này nay còn có cả cheese, tạo nên một món đồ uống trà kem sữa vị phô mai mặn mặn, béo ngậy pha chút chát nhẹ và ngọt dịu của sữa và trà.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0060', 'Cha yen – Thái Lan', '20000', '100','Không quá xa lạ với giới trẻ Việt Nam, Cha yen (tên gọi trong tiếng Thái của trà sữa Thái) là một điểm sáng về văn hóa ẩm thực đường phố Thái Lan, nhờ vào quá trình chế biến trà cực độc đáo. ','Cha yen có hai loại: trà đỏ và trà xanh. Trà đỏ là loại trà sữa truyền thống, trà xanh có mùi thơm nhẹ và thanh hơn. Cha yen có vị ngọt khá gắt, beo béo, có tác dụng giải nhiệt khá tốt khi dùng lạnh, rất phù hợp với khí hậu nóng quanh năm của xứ sở chùa vàng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('61', 'Trà sữa túi lọc', '20000', '100','Là xứ sở của trà, Việt Nam không thiếu những phiên bản trà sữa hảo hạng với giá thành từ trung bình đến cao cấp, nhưng trà sữa túi lọc hoàn toàn phản ánh đúng bản chất của người Việt Nam, cụ thể là người Sài Gòn: gọn nhẹ, gần gũi và dân dã.','Dân dã, tiện lợi và sáng tạo, trà sữa túi lọc là một phiên bản trà sữa đặc sắc của Việt Nam.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('62', 'Po cha – trà bơ Tây Tạng', '20000', '100','Nguyên liệu để pha trà bơ có lẽ là những cái tên còn khá xa lạ với người Việt: trà đen Pu-erh, bơ làm từ sữa bò Yak (đây là loại bò đặc trưng của vùng đất này) và muối Himalaya (một loại muối mỏ màu hồng có tác dụng chữa bệnh). Thời gian đun trà Pu-erh khoảng 1 tiếng, lâu hơn so với trà thông thường, sau đó người ta sẽ cho sữa và muối vào. Sau đó, họ dùng bình trà có tên là Chandong để hòa tan trà sữa vừa đun với bơ. Mùi vị thơm nhẹ, dễ uống, vừa giữ ấm tốt, vừa chống đói hiệu quả, nếu có dịp ghé thăm Tây Tạng, đừng quên trà bơ Po cha nhé.','Trà bơ Po cha không chỉ là thức uống truyền thống của người Tây Tạng, mà còn là “thần dược” giúp họ sinh tồn trong cái lạnh cắt da cắt thịt của vùng đất khắc nghiệt này.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('63', 'Masala chai – Pakistan, Ấn Độ', '20000', '100','Trà Masala chai là một thức uống giải khát có mùi vị trà, được làm bằng cách ủ trà đen với hỗn hợp các loại gia vị và thảo mộc Ấn Độ. Cho đến nay, Masala chai đã vươn ra toàn thế giới, ở một số nước, nó còn trở thành một nét đặc trưng chủ đạo của các quán cà phê cũng như phòng trà.','Để chế biến Masala chai, cách đơn giản nhất theo kiểu truyền thống là nấu cô bằng cách ninh lửa nhỏ hoặc nấu sôi hỗn hợp sữa và nước với trà được làm tơi, chất làm ngọt cùng tất cả các gia vị khác. Với hỗn hợp nguyên liệu lạ và đậm chất Nam Á, chắc chắn hương vị của Masala chai sẽ nồng đậm nhưng vẫn ngọt ngào, khiến du khách lưu luyến mãi.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('64', 'Trà sữa “hoàng gia” Nhật Bản', '20000', '100','Thật ra, tên gọi “trà sữa hoàng gia” là tên một thương hiệu trà sữa pha sẵn nổi tiếng của Nhật Bản, chứ không phải loại trà sữa được phục vụ trong cung đình. Tuy nhiên, món trà sữa này được nhiều người Nhật Bản yêu thích vì vị thơm ngon của nó.','Thay vì sử dụng nước pha với bột trà và thêm sữa đặc, người Nhật đun sữa đến khi vừa sôi thì cho bột trà vào. Khi ấy, mùi thơm khó cưỡng của trà sẽ bốc lên ngay lập tức, quyện với hương thơm của sữa đun sôi. Và đến khi dòng trà sữa hoàng gia ngọt ngào chạm đầu lưỡi, bạn sẽ hiểu vì sao nó được ưa chuộng ở Nhật Bản đến như vậy.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('65', 'Trà sữa trân châu Đài Loan', '20000', '100','Những li trà sữa với hạt trân châu đen hấp dẫn gây sốt trong giới trẻ Việt có nguồn gốc từ Đài Loan. Có thể nói, trà sữa Đài Loan đa dạng và phong phú bậc nhất trong số những phiên bản trà sữa trên khắp thế giới','Có đến gần 100 loại trà sữa cho bạn tha hồ lựa chọn nếu bước vào một quán trà sữa Đài Loan cùng nhiều loại hạt, trân châu vừa thích mắt vừa vui miệng. Đây là lí do khiến trà sữa Đài Loan được chào đón và yêu thích khi “đặt chân” đến các nước châu Á khác.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('66', 'TOCO SOCOLA ', '20000', '100','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng socola, một chút đắng, chút ngọt cực kì hấp dẫn.','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng, một chút đắng, chút ngọt cực kì hấp dẫn là sự kết hợp hoàn hảo của hương vị socola với hương thơm ngọt mát từ trà.Sẽ lại càng ngon hơn nếu Toco Socola được kết hợp với bánh pudding và trân trâu đen, tất cả sẽ làm nên một đồ uống tuyệt hảo khó quên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('67', 'TRÀ DÂU TẰM PHA LÊ TUYẾT', '20000', '100','Mứt dâu tằm hòa quyện cùng với trà xanh cùng những viên thạch băng tuyết dai dai cho ly trà dâu tằm thanh mát. Đặc biệt dâu tằm giúp trí não minh mẫn, thạch băng tuyết có lợi cho tiêu hóa.','Mứt dâu khi được hòa quyện cùng nước trà xanh tưởng chừng đối nghịch giữa ngọt – chát nhưng hóa ra lại bổ trợ tương hỗ cho nhau không ngờ, tạo nên một thức uống vừa quen vừa lạ.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('68', 'TRÀ SỮA PANDA ', '20000', '100','Hương trà nhài thơm mát cùng vị ngọt ngậy béo sữa kết hợp cùng sợi trân châu hoàng kim và trân châu sợi dai mềm.','Khi thưởng thức trà sữa Panda, khách hàng có thể cảm nhận rõ hương trà nhài thơm mát cùng vị ngọt ngậy béo của trà và sữa kết hợp cùng sợi trân châu dẻo dai. Trà của TocoToco, sau khi được thu hoạch từ những nông trường lớn, sẽ được ủ với hương hoa hài nên luôn tạo một hương vị nhẹ nhàng, thoang thoảng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('69', 'TRÀ SỮA BA ANH EM ', '20000', '100','Bộ ba topping thần thánh - "Trân châu hoàng kim dẻo mềm, thạch sương sáo thanh mát và bánh pudding mềm mịn" kết hợp hoàn hảo cùng vị ngậy béo của sữa và thanh mát của trà cho ra đời ly trà sữa ngon đúng điệu.','Là sự hòa quyện giữ vị nồng đặc trưng từ hồng trà sữa kết hợp với mùi sữa thơm ngậy. Đúng như tên gọi, trà sữa Ba anh em gồm 3 topping: trân châu dai dòn từ 100% tinh bột sắn, pudding, rau câu mềm, thanh, mát lạnh, vị ngọt tan dần đầu lưỡi, đánh thức từng tế bào vị giác.Thử Trà sữa Ba Anh Em ngay và liền nha, bạn sẽ không hối hận về lựa chọn của mình đâu!','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('71', 'SỮA TƯƠI CHÂN TRÂU ĐƯỜNG HỔ ', '20000', '100','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','Tiger Sugar là sự kết hợp hoàn hảo giữa vị ngọt đặc trưng của siro đường hổ quyện với vị ngậy béo của sữa tươi cùng trân châu dẻo dai uống rồi lại muốn thêm ly nữa','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('72', 'DÂU TẰM KEM PHÔ MAI', '20000', '100','Được làm từ trái dâu tằm tự nhiên, không sử dụng phẩm màu và hương liệu tổng hợp nên Dâu tằm kem phô mai hội tụ trọn vẹn hương vị thuần khiết nông sản Việt, giữ được màu sắc, hương vị nguyên bản của trái dâu tằm. Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy của kem phô mai chắc chắn sẽ mang đến một hành trình trải nghiệm hoàn toàn mới lạ cho vị giác của bạn.','Vị chát ngọt của trà kết hợp với vị chua ngọt từ mứt dâu tằm, hoà quyện cùng một chút ngậy ngậy, mặn mặn của kem phô mai mang lại trải nghiệm thú vị khi uống.','trà, bột sữa,dâu tằm,phô mai'),
	  ('73', 'Trà sữa khoai môn', '20000', '100','Trà sữa khoai môn tuy không phải là thức uống mới nhưng nó vẫn giữ được độ hot với giới trẻ, đặc biệt là vào các khoảng thời gian hè nắng nóng. ','Trà sữa khoai môn có vị béo béo của sữa, mùi thơm của khoai môn cùng với chút vị chát nhẹ của trà. Thức uống này không quá ngọt và ngậy như những loại trà sữa có kem cheese, vị ngọt thanh mà vẫn có chút béo bùi là điểm cộng lớn nhất của trà sữa khoai môn. Trà sữa khoai môn một số nơi sẽ dùng bột khoai môn để pha chế hoặc có thể dùng củ khoai môn tươi xay lấy nước sẽ nguyên chất hơn. ','siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('74', 'Trà sữa matcha đậu đỏ', '20000', '100','Nếu trà sữa matcha là thức uống quá quen thuộc và phổ biến thì trà sữa matcha đậu đỏ lại là sản phẩm mới, thích hợp giải nhiệt dành cho mùa hè nắng nóng. Trà sữa Matcha đậu đỏ về cơ bản vẫn là trà sữa trà xanh với vị chát nhẹ của trà, vị thơm mát của matcha cùng với chút ngọt nhẹ của sữa tươi.','Đặc điểm nổi bật so với các loại trà sữa khác: phần đậu đỏ được xem như topping được rải phía trên bề mặt cốc trà. Phần đậu đỏ này có mùi thơm và vị ngon ngọt đặc trưng, khi uống kết hợp cùng matcha the mát sẽ tạo nên sự hòa quyện hương vị hoàn hảo ở đầu lưỡi.','trà, bột sữa,đậu đỏ,phô mai'),
      ('75', 'Trà sữa Oreo Chocolate Cream', '20000', '100','Trong số các loại trà sữa phổ biến thì trà sữa Oreo Chocolate Cream là một loại trà sữa khá mới trong thời gian gần đây. Với những người hảo ngọt thì vị béo ngậy của cốc trà này sẽ làm bạn phải mê mẩn. Phần trà sữa thơm ngọt kết hợp cùng lớp bọt kem mặn, đặc biệt là mùi thơm quyến rũ của chocolate cùng bánh Oreo.',' Vị béo ngậy của lớp kem cùng vị ngọt của sữa trong trà sẽ không làm bạn cảm thấy quá ngán nhờ chút đắng mà chocolate cùng vụn bánh Oreo mang lại.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('76', 'Trà sữa Pudding đậu đỏ', '20000', '100','Đây là loại trà sữa có topping gồm phần pudding trứng cùng với hạt đậu đỏ. Về phần trà sữa thì ngoài vị chát nhẹ cùng vị ngọt béo của sữa và trà thì điểm nhấn của cốc trà sữa này nằm ở phần pudding trứng cùng đậu đỏ phía trên.','Pudding trứng mềm mại, có vị ngọt và thơm, pha chút béo ngậy của vani và có màu vàng óng ngọt ngào, đi kèm đó là những hạt đậu đỏ mềm nhuyễn cũng có vị ngọt nhưng lại khá bùi khi nhai. 2 nguyên liệu này kết hợp cùng trà sữa tạo thành trà sữa Pudding đậu đỏ thích hợp giải nhiệt mùa hè','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('77', 'Trà sữa trân châu đen và trà sữa trân châu trắng', '20000', '100','Trà sữa trân châu đen và trà sữa trân châu trắng hẳn là 2 thức uống có mặt lâu nhất trong các menu tại các quán trà sữa cũng như các quán ăn vặt. Không phải tự nhiên mà 2 loại thức uống này vẫn tồn tại và được lòng nhiều người bên cạnh hàng loạt các sản phẩm trà sữa mới.','Trà sữa trân châu đen luôn là sự kết hợp hoàn hảo giữa trà đen, sữa tươi cùng hạt trân châu mềm, dai và có chút vị ngọt nhẹ. Uống và cảm nhận vị chát của trà, vị ngọt lẫn chút thơm của sữa cùng với những hạt trân châu đen dai dai hẳn là một lựa chọn khá hoàn hảo cho không chỉ riêng mùa hè.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('78', ' Trà sữa sương sáo', '20000', '100','Sương sáo, sương sa là những nguyên liệu phổ biến tại các tỉnh miền Nam và cực thích hợp cho những ngày hè nắng nóng. Sương sáo có tính giải nhiệt cao cùng với đó là nhiều công dụng tốt cho sức khỏe. Trà sữa sương sáo là sự kết hợp giữa trà sữa truyền thống với phần sương sáo mát lạnh.','Đặc điểm đặc trưng so với các loại trà sữa khác: có vị không quá ngọt béo hay ngọt ngậy như các loại trà sữa khác. Thay vào đó là vị ngọt thanh của sương sáo mà vẫn có chút thơm béo béo của sữa tươi và vị chát nhẹ của trà. Trà sữa sương sáo có độ ngọt vừa phải, có mùi thơm đặc trưng cũng như có tính giải khát cao.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('779', 'Trà sữa Earl Grey', '20000', '100','Trà sữa Earl Grey hay còn gọi là Trà Bá Tước là một loại trà sữa độc đáo được làm từ trà xuất xứ từ nước Anh với công đoạn ướp khá cầu kỳ. Trà sữa Earl Grey có vị khá chát và đắng nhẹ, đặc biệt là mùi thơm rất đặc trưng mà không phải loại trà nào cũng có.','Đặc điểm đặc trưng khác với các loại trà sữa khác: Điểm nhấn của trà sữa Earl Grey là tinh dầu cam đắng Bergamot, kết hợp cùng vị béo ngậy của lớp kem mặn phía trên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('80', 'Trà sữa Caramel', '20000', '100','Caramel hẳn là một món ăn, một nguyên liệu phổ biến đặc biệt với giới trẻ. Chỉ riêng caramel cũng có thể kết hợp được với vô số nguyên liệu khác để tạo thành những món ăn ngon và hấp dẫn. Trà sữa caramel được làm từ trà sữa truyền thống kết hợp cùng lớp kem caramel thơm và béo ngậy.','Đặc điểm đặc trưng so với các loại trà sữa khác: phần trà sữa ngọt dịu kết hợp cùng lớp kem caramel thơm thơm, béo béo, tạo nên tổng thể một thức uống không quá ngọt những vẫn có mùi béo ngậy hấp dẫn nhiều người.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('89', 'Trà sữa Cà phê', '20000', '100','Nhắc tới cà phê là nhắc tới một loại đồ uống truyền thống của người dân Việt Nam. Hương vị của cà phê có chút đắng, khác với vị đắng của chocolate. Đặc biệt thì cà phê cũng có mùi thơm quyến rũ mà chỉ cần ngửi cũng muốn được uống thử. Trà sữa cà phê hẳn là sự kết hợp khá độc đáo giữa 2 nguyên liệu tưởng chừng có ít sự liên quan này với nhau.','Đặc điểm đặc trưng so với các loại trà sữa khác:  cho dù có mùi vị cà phê nhưng vị chát nhẹ của trà đen vẫn được giữ nguyên, vị thơm của trà và cà phê không những không át nhau mà còn hòa quyện tạo nên mùi hương độc đáo. Ngoài ra chút vị đắng nhẹ của cà phê cũng rất thích hợp để kết hợp cùng vị ngọt bùi của sữa.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường' ),
	  ('88', 'Lục trà sữa', '20000', '100','Lục trà sữa là một loại trà sữa phổ biến và có mặt hầu như các menu của các tiệm trà sữa. Lục trà sữa ngoài vị chát nhẹ thì còn có vị thơm nồng và ngọt ngọt của sữa. Lục trà sữa có nhiều sữa hơn so với hồng trà sữa.','Đặc điểm đặc trưng so với các loại trà sữa khác: thức uống này có thể kết hợp thêm các vị như kiwi, dâu, táo, nho,…để tăng thêm độ thơm ngon. Lục trà sữa chủ yếu hợp với topping như trân châu đen, trân châu trắng','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('897', 'Trà sữa cheese milk foam', '20000', '100','Trà sữa cheese milk foam là một loại đồ uống được giới trẻ đặc biệt yêu thích thời gian đổ lại đây. Ngoài vị trà sữa truyền thống thì cốc trà còn được thêm một lớp kem sữa béo béo, ngậy ngậy tràn mùi thơm.','Điểm đặc trưng so với các loại trà sữa khác: lớp kem sữa này nay còn có cả cheese, tạo nên một món đồ uống trà kem sữa vị phô mai mặn mặn, béo ngậy pha chút chát nhẹ và ngọt dịu của sữa và trà.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('96', 'Cha yen – Thái Lan', '20000', '100','Không quá xa lạ với giới trẻ Việt Nam, Cha yen (tên gọi trong tiếng Thái của trà sữa Thái) là một điểm sáng về văn hóa ẩm thực đường phố Thái Lan, nhờ vào quá trình chế biến trà cực độc đáo. ','Cha yen có hai loại: trà đỏ và trà xanh. Trà đỏ là loại trà sữa truyền thống, trà xanh có mùi thơm nhẹ và thanh hơn. Cha yen có vị ngọt khá gắt, beo béo, có tác dụng giải nhiệt khá tốt khi dùng lạnh, rất phù hợp với khí hậu nóng quanh năm của xứ sở chùa vàng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('95', 'Trà sữa túi lọc', '20000', '100','Là xứ sở của trà, Việt Nam không thiếu những phiên bản trà sữa hảo hạng với giá thành từ trung bình đến cao cấp, nhưng trà sữa túi lọc hoàn toàn phản ánh đúng bản chất của người Việt Nam, cụ thể là người Sài Gòn: gọn nhẹ, gần gũi và dân dã.','Dân dã, tiện lợi và sáng tạo, trà sữa túi lọc là một phiên bản trà sữa đặc sắc của Việt Nam.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('94', 'Po cha – trà bơ Tây Tạng', '20000', '100','Nguyên liệu để pha trà bơ có lẽ là những cái tên còn khá xa lạ với người Việt: trà đen Pu-erh, bơ làm từ sữa bò Yak (đây là loại bò đặc trưng của vùng đất này) và muối Himalaya (một loại muối mỏ màu hồng có tác dụng chữa bệnh). Thời gian đun trà Pu-erh khoảng 1 tiếng, lâu hơn so với trà thông thường, sau đó người ta sẽ cho sữa và muối vào. Sau đó, họ dùng bình trà có tên là Chandong để hòa tan trà sữa vừa đun với bơ. Mùi vị thơm nhẹ, dễ uống, vừa giữ ấm tốt, vừa chống đói hiệu quả, nếu có dịp ghé thăm Tây Tạng, đừng quên trà bơ Po cha nhé.','Trà bơ Po cha không chỉ là thức uống truyền thống của người Tây Tạng, mà còn là “thần dược” giúp họ sinh tồn trong cái lạnh cắt da cắt thịt của vùng đất khắc nghiệt này.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('93', 'Masala chai – Pakistan, Ấn Độ', '20000', '100','Trà Masala chai là một thức uống giải khát có mùi vị trà, được làm bằng cách ủ trà đen với hỗn hợp các loại gia vị và thảo mộc Ấn Độ. Cho đến nay, Masala chai đã vươn ra toàn thế giới, ở một số nước, nó còn trở thành một nét đặc trưng chủ đạo của các quán cà phê cũng như phòng trà.','Để chế biến Masala chai, cách đơn giản nhất theo kiểu truyền thống là nấu cô bằng cách ninh lửa nhỏ hoặc nấu sôi hỗn hợp sữa và nước với trà được làm tơi, chất làm ngọt cùng tất cả các gia vị khác. Với hỗn hợp nguyên liệu lạ và đậm chất Nam Á, chắc chắn hương vị của Masala chai sẽ nồng đậm nhưng vẫn ngọt ngào, khiến du khách lưu luyến mãi.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('92', 'Trà sữa “hoàng gia” Nhật Bản', '20000', '100','Thật ra, tên gọi “trà sữa hoàng gia” là tên một thương hiệu trà sữa pha sẵn nổi tiếng của Nhật Bản, chứ không phải loại trà sữa được phục vụ trong cung đình. Tuy nhiên, món trà sữa này được nhiều người Nhật Bản yêu thích vì vị thơm ngon của nó.','Thay vì sử dụng nước pha với bột trà và thêm sữa đặc, người Nhật đun sữa đến khi vừa sôi thì cho bột trà vào. Khi ấy, mùi thơm khó cưỡng của trà sẽ bốc lên ngay lập tức, quyện với hương thơm của sữa đun sôi. Và đến khi dòng trà sữa hoàng gia ngọt ngào chạm đầu lưỡi, bạn sẽ hiểu vì sao nó được ưa chuộng ở Nhật Bản đến như vậy.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('91', 'Trà sữa trân châu Đài Loan', '20000', '100','Những li trà sữa với hạt trân châu đen hấp dẫn gây sốt trong giới trẻ Việt có nguồn gốc từ Đài Loan. Có thể nói, trà sữa Đài Loan đa dạng và phong phú bậc nhất trong số những phiên bản trà sữa trên khắp thế giới','Có đến gần 100 loại trà sữa cho bạn tha hồ lựa chọn nếu bước vào một quán trà sữa Đài Loan cùng nhiều loại hạt, trân châu vừa thích mắt vừa vui miệng. Đây là lí do khiến trà sữa Đài Loan được chào đón và yêu thích khi “đặt chân” đến các nước châu Á khác.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('82', 'TOCO SOCOLA ', '20000', '100','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng socola, một chút đắng, chút ngọt cực kì hấp dẫn.','Toco Socola chắc chắn sẽ khiến bạn mê mẩn bởi hương thơm đặc trưng, một chút đắng, chút ngọt cực kì hấp dẫn là sự kết hợp hoàn hảo của hương vị socola với hương thơm ngọt mát từ trà.Sẽ lại càng ngon hơn nếu Toco Socola được kết hợp với bánh pudding và trân trâu đen, tất cả sẽ làm nên một đồ uống tuyệt hảo khó quên.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('83', 'TRÀ DÂU TẰM PHA LÊ TUYẾT', '20000', '100','Mứt dâu tằm hòa quyện cùng với trà xanh cùng những viên thạch băng tuyết dai dai cho ly trà dâu tằm thanh mát. Đặc biệt dâu tằm giúp trí não minh mẫn, thạch băng tuyết có lợi cho tiêu hóa.','Mứt dâu khi được hòa quyện cùng nước trà xanh tưởng chừng đối nghịch giữa ngọt – chát nhưng hóa ra lại bổ trợ tương hỗ cho nhau không ngờ, tạo nên một thức uống vừa quen vừa lạ.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('101', 'TRÀ SỮA PANDA ', '20000', '100','Hương trà nhài thơm mát cùng vị ngọt ngậy béo sữa kết hợp cùng sợi trân châu hoàng kim và trân châu sợi dai mềm.','Khi thưởng thức trà sữa Panda, khách hàng có thể cảm nhận rõ hương trà nhài thơm mát cùng vị ngọt ngậy béo của trà và sữa kết hợp cùng sợi trân châu dẻo dai. Trà của TocoToco, sau khi được thu hoạch từ những nông trường lớn, sẽ được ủ với hương hoa hài nên luôn tạo một hương vị nhẹ nhàng, thoang thoảng.','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường'),
	  ('0102', 'TRÀ SỮA BA ANH EM ', '20000', '100','Bộ ba topping thần thánh - "Trân châu hoàng kim dẻo mềm, thạch sương sáo thanh mát và bánh pudding mềm mịn" kết hợp hoàn hảo cùng vị ngậy béo của sữa và thanh mát của trà cho ra đời ly trà sữa ngon đúng điệu.','Là sự hòa quyện giữ vị nồng đặc trưng từ hồng trà sữa kết hợp với mùi sữa thơm ngậy. Đúng như tên gọi, trà sữa Ba anh em gồm 3 topping: trân châu dai dòn từ 100% tinh bột sắn, pudding, rau câu mềm, thanh, mát lạnh, vị ngọt tan dần đầu lưỡi, đánh thức từng tế bào vị giác.Thử Trà sữa Ba Anh Em ngay và liền nha, bạn sẽ không hối hận về lựa chọn của mình đâu!','trà, bột sữa,đậu đỏ,phô mai,siro đường hổ, sữa tươi, trân châu, đá lạnh,đường');

select * from Users;
select * from Items;
select * from Orders;
select * from OrderDetails;
